#!/usr/bin/env python3
"""Bundle tools/i18n/*.json into web/i18n.js for the web version.

    python3 tools/build_i18n.py

en.json is the reference: every language must have the same keys, array
lengths and {placeholders}, and poem.del must be a suffix of
poem.pre + poem.apple (the page types the apple, then backspaces del).
The language screen lists languages in ORDER.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "i18n")
OUT = os.path.join(HERE, "..", "web", "i18n.js")
ORDER = ["zh-Hant", "zh-Hans", "en", "ja", "ko", "es", "fr", "de", "pt",
         "it", "ru", "vi", "th", "id", "tr", "ar", "hi"]


def shape(v):
    if isinstance(v, dict):
        return {k: shape(x) for k, x in v.items()}
    if isinstance(v, list):
        return len(v)
    return "str"


def placeholders(v):
    return sorted(re.findall(r"\{\w+\}", json.dumps(v, ensure_ascii=False)))


def main():
    langs = {c: json.load(open(os.path.join(SRC, c + ".json"), encoding="utf-8")) for c in ORDER}
    en = langs["en"]
    for code, d in langs.items():
        assert shape(d) == shape(en), f"{code}: keys or array lengths differ from en"
        for k in en:
            assert placeholders(d[k]) == placeholders(en[k]), f"{code}.{k}: placeholders differ"
        p = d["poem"]
        assert (p["pre"] + p["apple"]).endswith(p["del"]), f"{code}: poem.del is not a suffix"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build_i18n.py from tools/i18n/*.json.\n")
        f.write("window.I18N = ")
        json.dump(langs, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    print(f"{len(langs)} languages -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
