#!/usr/bin/env python3
"""Pack the Bad Apple!! PV into web/frames.js for the web version.

    python3 tools/build_web.py badapple.mp4
    python3 tools/build_i18n.py          # re-stamps the script versions in index.html

Frames are 80x60 black-and-white bitmaps (1 = white), packed 8 pixels per
byte, XORed with the previous frame so still areas become zeros, then
raw-deflated and base64-encoded. The page undoes this with
DecompressionStream("deflate-raw").
"""
import argparse
import base64
import os
import zlib

import numpy as np

from build import read_frames

WIDTH, HEIGHT, FPS = 80, 60, 30


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("video")
    p.add_argument("-o", "--out", default=os.path.join(
        os.path.dirname(__file__), "..", "web", "frames.js"))
    args = p.parse_args()

    frames = read_frames(args.video, WIDTH, HEIGHT, FPS)
    packed = np.packbits(frames.reshape(len(frames), -1), axis=1)
    delta = packed.copy()
    delta[1:] ^= packed[:-1]
    z = zlib.compressobj(9, zlib.DEFLATED, -15)
    blob = z.compress(delta.tobytes()) + z.flush()

    with open(args.out, "w") as f:
        f.write("// Generated by tools/build_web.py: Bad Apple!! PV, "
                f"{len(frames)} frames, {WIDTH}x{HEIGHT} 1-bit, {FPS} fps.\n")
        f.write(f"window.BAD_APPLE = {{w: {WIDTH}, h: {HEIGHT}, fps: {FPS}, "
                f"n: {len(frames)}, data: \"{base64.b64encode(blob).decode()}\"}};\n")
    print(f"{len(frames)} frames -> {args.out} ({len(blob)} bytes deflated)")


if __name__ == "__main__":
    main()
